// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * Protocol-level agent configuration.
 *
 * This is a simplified version used for RegisterAgent operations.
 * The core crate has a more detailed AgentConfig for runtime use.
 */
export type AgentConfig = { 
/**
 * Unique identifier for this agent.
 */
id: AgentId, 
/**
 * Human-readable name for this agent.
 */
name: string, 
/**
 * Role/specialization of this agent (as a string for flexibility).
 */
role: string, 
/**
 * Optional custom system prompt for this agent.
 */
system_prompt: string | null, 
/**
 * Optional list of allowed tool names.
 *
 * If provided, this agent will only be able to use tools in this list.
 * If None, the agent can use all available tools.
 */
allowed_tools: Array<string> | null, 
/**
 * Maximum number of concurrent tasks this agent can handle.
 *
 * Defaults to 1 for sequential task execution.
 */
max_concurrent_tasks: number, };
