// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { MessageType } from "./MessageType";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A message sent from one agent to another.
 */
export type AgentMessage = { 
/**
 * Unique identifier for this message.
 */
id: string, 
/**
 * Agent sending the message.
 */
from: AgentId, 
/**
 * Agent receiving the message.
 */
to: AgentId, 
/**
 * Type of message.
 */
message_type: MessageType, 
/**
 * Message payload (flexible JSON structure).
 */
payload: JsonValue, 
/**
 * Optional reference to a previous message (for responses).
 */
in_reply_to: string | null, 
/**
 * Timestamp when the message was created (milliseconds since UNIX epoch).
 */
timestamp: bigint, };
