// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unique identifier for an agent within a session.
 *
 * Each agent in a multi-agent session has a unique ID that is used to route
 * operations and track events. The special ID "default" is used for backward
 * compatibility with single-agent sessions.
 */
export type AgentId = string;
