// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of message being sent between agents.
 */
export type MessageType = "request" | "response" | "notification" | "query";
