// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMessage } from "./AgentMessage";
import type { MessagePriority } from "./MessagePriority";

/**
 * A message with priority and routing metadata.
 */
export type QueuedMessage = { 
/**
 * The actual message.
 */
message: AgentMessage, 
/**
 * Priority for processing.
 */
priority: MessagePriority, 
/**
 * Whether this message requires a response.
 */
requires_response: boolean, 
/**
 * Timeout in milliseconds (None = no timeout).
 */
timeout_ms: bigint | null, };
